In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [12]:
df.iloc[10: 16, 7: 11]

,job_posted_date,job_no_degree_mention,job_health_insurance,job_country
10,2023-04-17 13:27:32,True,False,Switzerland
11,2023-11-03 13:06:51,False,True,United States
12,2023-12-22 13:24:41,False,False,France
13,2023-11-15 13:08:52,True,True,United States
14,2023-07-13 13:17:51,False,False,Brazil
15,2023-10-19 13:37:16,False,False,United Kingdom

In [34]:
df.loc[ :, "job_country" :"salary_hour_avg"].sort_values('salary_year_avg').dropna(subset= 'salary_rate')

          job_country salary_rate  salary_year_avg  salary_hour_avg
665729         Brazil        year          15000.0              NaN
380187     Bangladesh        year          16500.0              NaN
130855      Australia        year          20000.0              NaN
535260  United States        year          23496.0              NaN
213687       Pakistan        year          24000.0              NaN
...               ...         ...              ...              ...
784068          Sudan        hour              NaN        54.420002
784267  United States        hour              NaN        61.159996
785111  United States        hour              NaN        61.159996
785476  United States        hour              NaN        47.620003
785492  United States        hour              NaN        47.620003

[33067 rows x 4 columns]