In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# DataFrame Copy
df_original = df.copy()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
#Ceate new data frame 
df_altered = df_original 
df_altered.loc[: ,'salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [4]:
#Calculating the median salary 
median_salary_year = df_altered['salary_year_avg'].median()
#filling the missing values with the median salary 
df_altered['salary_year_avg']= df['salary_year_avg'].fillna(median_salary_year)

In [6]:
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [7]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [9]:
id(df_altered )== id(df_original)

True

In [ ]:
#by using the fonction copy() instead of creating new df 
df_original = df.copy()

In [15]:
#Calculating the median salary 
median_salary = df_original['salary_year_avg'].median()
#filling the missing values with the median salary
df_original['salary_year_avg'] = df_original['salary_year_avg'].fillna(median_salary)

In [16]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [17]:
df.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [ ]:
#get a random sample of data with or wihtout a fixed row number 
df.sample(n =5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
618131,Data Engineer,Data Engineer Level I (Entry Level),"Gadag-Betageri, Karnataka, India",via Talents Jobs,Full-time,False,India,2023-09-24 12:06:32,False,False,India,NaN,NaN,NaN,Aerospace and Defense Web Geek Technology,NaN,NaN
729180,Senior Data Engineer,Sr. Data Engineer – Integrations,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-06-21 21:10:01,False,True,United States,NaN,NaN,NaN,Zensar Technologies,"['java', 'javascript', 'oracle', 'flow']","{'cloud': ['oracle'], 'other': ['flow'], 'prog..."
24688,Data Scientist,JUNIOR / MID/ SENIOR / EXPERT Data Scientist,"İstanbul, Türkiye",via LinkedIn,Full-time,False,Turkey,2023-09-04 13:29:19,False,False,Turkey,NaN,NaN,NaN,LENORA Bilişim Teknolojileri,"['sql', 'python', 'sas', 'sas', 'r', 'aws', 'a...","{'analyst_tools': ['sas', 'spss'], 'cloud': ['..."
31897,Data Analyst,Analytics Manager,Australia,via Jooble,Full-time,False,Australia,2023-10-14 13:09:31,True,False,Australia,NaN,NaN,NaN,JOBX Pty Ltd,['sql'],{'programming': ['sql']}
707731,Senior Data Scientist,Senior Data Scientist (REMOTE),Anywhere,via ZipRecruiter,Full-time,True,"California, United States",2023-10-17 02:24:04,False,False,United States,NaN,NaN,NaN,Merck,"['python', 'r', 'sql', 'aws', 'databricks']","{'cloud': ['aws', 'databricks'], 'programming'..."

In [23]:
#get a random sample of the data with fraction 
df.sample(frac = .1, random_state = 42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306479,Data Analyst,Data Analyst - Mid Level,"Ann Arbor, MI",via LinkedIn,Full-time and Temp work,False,"Illinois, United States",2023-10-16 17:24:54,True,False,United States,NaN,NaN,NaN,Procom,"['sql', 'sql server', 'phoenix', 'atlassian', ...","{'async': ['jira', 'confluence'], 'databases':..."
321355,Data Analyst,"Data Analyst Mechelen, Belgium Posted on 08/04...","Mechelen, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-12-14 17:29:59,False,False,Belgium,NaN,NaN,NaN,TELENET,['gdpr'],{'libraries': ['gdpr']}
462990,Cloud Engineer,Senior Control System Engineer,"Sydney NSW, Australia",via Jobs Trabajo.org,Full-time,False,Australia,2023-04-10 14:10:04,False,False,Australia,NaN,NaN,NaN,SICE Pty Ltd,"['word', 'excel', 'visio']","{'analyst_tools': ['word', 'excel', 'visio']}"
350032,Senior Data Scientist,Senior Data Scientist I (NLP expert),Singapore,via Recruit.net,Full-time,False,Singapore,2023-06-08 00:01:51,False,False,Singapore,NaN,NaN,NaN,Kkt Technology Pte. Ltd.,"['sql', 'aws', 'scikit-learn', 'pandas', 'nump...","{'cloud': ['aws'], 'libraries': ['scikit-learn..."
374965,Data Scientist,Sr. Data Scientist,"Austin, TX",via BeBee,Full-time,False,Sudan,2023-07-08 18:36:50,False,True,Sudan,NaN,NaN,NaN,eBay,"['python', 'java', 'scala', 'sql', 'nosql', 't...","{'libraries': ['tensorflow', 'pytorch', 'hadoo..."

In [ ]:
#get a random sample of data sampling without replacement, so a row can be picked at most once
df.sample(frac= .2 , replace = False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
671340,Senior Data Engineer,Senior Data Platform Engineer,"Amsterdam, Netherlands",via LinkedIn,Full-time,False,Netherlands,2023-12-11 10:56:14,False,False,Netherlands,NaN,NaN,NaN,Harnham,"['java', 'python', 'scala', 'sql', 'nosql', 'a...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
389548,Data Analyst,Junior Data Analyst *,"Nuremberg, Germany",via BeBee,Full-time,False,Germany,2023-10-31 18:11:59,True,False,Germany,NaN,NaN,NaN,Studyflix GmbH,"['r', 'python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
484278,Senior Data Engineer,Senior Cloud Data Engineer,"Warsaw, Poland",via Linkedin,Full-time,False,Poland,2023-01-04 14:38:25,True,False,Poland,NaN,NaN,NaN,SEB,"['sql', 'python', 'bigquery', 'gcp', 'git']","{'cloud': ['bigquery', 'gcp'], 'other': ['git'..."
153903,Data Engineer,Product Support Engineer-Data Security Vancouv...,"Vancouver, BC, Canada",via BeBee Canada,Full-time,False,Canada,2023-09-16 08:15:15,False,False,Canada,NaN,NaN,NaN,Imperva,"['perl', 'python', 'shell', 'sql', 'mysql', 'd...","{'cloud': ['azure', 'aws', 'oracle'], 'databas..."
353318,Senior Data Scientist,Senior Principal Data Scientist,"Cambridge, MA",via The Muse,Full-time,False,"New York, United States",2023-05-01 23:03:11,False,False,United States,NaN,NaN,NaN,CarGurus,"['go', 'python', 'sql']","{'programming': ['go', 'python', 'sql']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521863,Data Analyst,Data Analyst,"Madrid, Spain",via BeBee,Full-time,False,Spain,2023-09-08 11:57:29,False,False,Spain,NaN,NaN,NaN,Ferchau,"['python', 'sql', 'sql server']","{'databases': ['sql server'], 'programming': [..."
269742,Data Analyst,Junior Safety Data Analyst,"Manila, Metro Manila, Philippines",via Indeed,Full-time,False,Philippines,2023-03-27 07:26:54,False,False,Philippines,NaN,NaN,NaN,Labcorp,NaN,NaN
637646,Data Analyst,Analytics Engineer H/F,"Paris, France",via JobTeaser - Talentify,Full-time,False,France,2023-02-20 12:51:08,False,False,France,NaN,NaN,NaN,JobTeaser,"['sql', 'postgresql', 'airflow', 'tableau', 'n...","{'analyst_tools': ['tableau'], 'async': ['noti..."
775708,Data Analyst,Data Analyst for Data Analytics and Mining (Py...,Anywhere,via Dice,Contractor,True,"California, United States",2023-03-01 01:01:19,False,False,United States,NaN,NaN,NaN,"OSI Engineering, Inc.","['sql', 'r', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
44263,Data Engineer,Data Engineer,"Bengaluru, Karnataka, India",via BeBee India,Full-time,False,India,2023-05-09 06:31:40,True,False,India,NaN,NaN,NaN,SchbangQ,"['go', 'sap', 'flow']","{'analyst_tools': ['sap'], 'other': ['flow'], ..."